### ISSUE TITLE
flood.py is not storing rhsm.log

### ISSUE THREAD

**Issue by sthirugn** [JacobCallahan/content-host-d#16]
```sh
python /content-host-d/flood.py --satellite satellite.test.com --name test1 --key rhel7_ak  --organization ACME --count 100 --exit-criteria register  --rhsm-log-dir logs
```
After running the above command, `flood.py` correctly stored the logs.

but logs/ subfolder had created empty log files for container hosts.  When I see journald `journalctl --since "2018-03-16 14:38:45" | grep docker`:

```sh
Mar 16 15:38:14 container.host.test.com dockerd-current[13955]: tail: cannot open '/var/log/rhsm/rhsm.log' for reading: Permission denied
```

**Comment by sthirugn** [comment]
this fails when selinux is enforced.  Confirmed that it logs correct after `setenforce 0`

**Comment by JacobCallahan** [comment]
Unfortunately, there is nothing we can do about this from the script's end. Docker-py only allows for setting read/write modes during bind declarations.
https://github.com/docker/docker-py/blob/master/docker/utils/utils.py#L202
