### ISSUE TITLE
Help output for hypervisors and guests options unclear

### ISSUE THREAD

**Issue by swadeley** [JacobCallahan/content-host-d#33]
Hello

"  --hypervisors HYPERVISORS
                        The number of hypervisors to create. This is only to
                        be used with the 'guest' tag"

Should that be: "with the 'guests' tag"?

  "--guests GUESTS       The number of guests per hypervisor to create. This is
                        only to be used with the 'guest' tag"

Should that be: "with the 'hypervisors' tag"?

Thank you

**Comment by JacobCallahan** [comment]
absolutely! feel free to send a PR :)

**Comment by swadeley** [comment]
Hello

that is very kind of you I am sure. Unfortunately, I have no perms to add assignees or reviewers, so here is the pull request:
https://github.com/JacobCallahan/content-host-d/pull/34
