### ISSUE TITLE
Give user an option to store rhsm.log from the containers

### ISSUE THREAD

**Issue by sthirugn** [JacobCallahan/content-host-d#9]
Request created from here: https://github.com/JacobCallahan/content-host-d/pull/8#issuecomment-371899738
`docker run ... -v $(pwd)/local.log:/etc/rhsm/rhsm.log ... ch-d:rhel7`

**Comment by JacobCallahan** [comment]
There are a few ways we could do this, but my main thought is this:

User specifies a local rhsm log directory ```--rhsm-log-dir /path/to/logs```
The script checks of the local directory exists, creating it if not. Another check if the path is absolute, resolving if not.
The script then will create a local file to store the logs to. Naming convention could be hostname.log.
The local log should persist after container teardown/cleanup.
